name: deploy

on:
  push:
    branches: [ "*" ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-south-1
  SAM_ARTIFACTS_BUCKET: weatherio-sam-artifacts-771817872925-ap-south-1
  STACK_NAME: weatherio

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::771817872925:role/WeatherioGithubActionsDeployer
          role-session-name: weatherio-github
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: Build SAM
        run: sam build --use-container

      - name: Package template
        run: sam package --s3-bucket ${{ env.SAM_ARTIFACTS_BUCKET }} --region ${{ env.AWS_REGION }} --output-template-file packaged.yaml

      - name: Deploy stack
        run: >
          sam deploy
          --template-file packaged.yaml
          --stack-name ${{ env.STACK_NAME }}
          --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM
          --region ${{ env.AWS_REGION }}
          --no-fail-on-empty-changeset
          --parameter-overrides MongoUri='${{ secrets.MONGO_URI }}'

      - name: Show API outputs
        run: |
          aws cloudformation describe-stacks --stack-name ${{ env.STACK_NAME }} --query "Stacks[0].Outputs" --output table
